import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  curriculumSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Course design',
      collapsed: false,
      link: {type: 'doc', id: '00-course-overview/01-overview'},
      items: [
        '00-course-overview/01-overview',
        '00-course-overview/02-objectives-and-outcomes',
        '00-course-overview/03-learning-progression',
        '00-course-overview/04-assessment-strategy',
        '00-course-overview/05-ai-policy',
        '00-course-overview/06-weekly-schedule',
      ],
    },
    {
      type: 'category',
      label: 'Part I — Testing fundamentals',
      link: {type: 'doc', id: 'part-1-testing-fundamentals/00-module-overview'},
      items: [
        'part-1-testing-fundamentals/01-what-is-software-testing',
        'part-1-testing-fundamentals/02-manual-vs-automation-testing',
        'part-1-testing-fundamentals/03-test-strategy-and-the-test-pyramid',
        'part-1-testing-fundamentals/04-regression-smoke-sanity-and-test-quality',
      ],
    },
    {
      type: 'category',
      label: 'Part II — Programming fundamentals',
      link: {type: 'doc', id: 'part-2-programming-fundamentals/00-module-overview'},
      items: [
        'part-2-programming-fundamentals/01-thinking-like-a-programmer',
        'part-2-programming-fundamentals/02-data-types',
        'part-2-programming-fundamentals/03-variables-and-constants',
        'part-2-programming-fundamentals/04-operators',
        'part-2-programming-fundamentals/05-conditional-logic',
        'part-2-programming-fundamentals/06-loops',
        'part-2-programming-fundamentals/07-functions',
        'part-2-programming-fundamentals/08-arrays',
        'part-2-programming-fundamentals/09-objects',
        'part-2-programming-fundamentals/10-typescript-fundamentals',
        'part-2-programming-fundamentals/11-error-handling',
        'part-2-programming-fundamentals/12-asynchronous-programming',
        'part-2-programming-fundamentals/13-json',
      ],
    },
    {
      type: 'category',
      label: 'Part III — Automation fundamentals',
      link: {type: 'doc', id: 'part-3-automation-fundamentals/00-module-overview'},
      items: [
        'part-3-automation-fundamentals/01-principles-of-good-automated-tests',
        'part-3-automation-fundamentals/02-test-automation-architecture',
      ],
    },
    {
      type: 'category',
      label: 'Part IV — API testing',
      className: 'sidebar-wip',
      link: {type: 'doc', id: 'part-4-api-testing-and-automation/00-module-overview'},
      items: [
        'part-4-api-testing-and-automation/01-http-fundamentals',
        'part-4-api-testing-and-automation/02-rest-api-and-crud',
        'part-4-api-testing-and-automation/03-designing-api-test-cases',
        'part-4-api-testing-and-automation/04-playwright-api-testing-basics',
        'part-4-api-testing-and-automation/05-playwright-api-write-operations',
        'part-4-api-testing-and-automation/06-api-authentication-and-authorization',
        'part-4-api-testing-and-automation/07-reusable-api-clients-and-models',
        'part-4-api-testing-and-automation/08-api-test-data-and-environments',
      ],
    },
    {
      type: 'category',
      label: 'Part V — Web automation',
      className: 'sidebar-wip',
      link: {type: 'doc', id: 'part-5-web-automation-playwright/00-module-overview'},
      items: [
        'part-5-web-automation-playwright/01-playwright-fundamentals',
        'part-5-web-automation-playwright/02-locator-strategy',
        'part-5-web-automation-playwright/03-browser-actions',
        'part-5-web-automation-playwright/04-web-assertions',
        'part-5-web-automation-playwright/05-synchronization-and-flaky-tests',
      ],
    },
    {
      type: 'category',
      label: 'Part VI — Framework engineering',
      className: 'sidebar-wip',
      link: {type: 'doc', id: 'part-6-framework-engineering/00-module-overview'},
      items: [
        'part-6-framework-engineering/01-page-object-model',
        'part-6-framework-engineering/02-fixtures',
        'part-6-framework-engineering/03-authentication-strategies',
        'part-6-framework-engineering/04-test-data-management',
        'part-6-framework-engineering/05-configuration',
        'part-6-framework-engineering/06-cross-browser-and-mobile',
        'part-6-framework-engineering/07-parallel-execution-and-sharding',
        'part-6-framework-engineering/08-debugging-playwright-tests',
        'part-6-framework-engineering/09-diagnosing-flaky-tests',
      ],
    },
    {
      type: 'category',
      label: 'Part VII — CI/CD',
      className: 'sidebar-wip',
      link: {type: 'doc', id: 'part-7-cicd/00-module-overview'},
      items: [
        'part-7-cicd/01-git-for-automation-engineers',
        'part-7-cicd/02-jenkins-pipelines',
        'part-7-cicd/03-docker-for-test-automation',
      ],
    },
    {
      type: 'category',
      label: 'Part VIII — Professional engineering',
      className: 'sidebar-wip',
      link: {type: 'doc', id: 'part-8-professional-engineering/00-module-overview'},
      items: [
        'part-8-professional-engineering/01-clean-code-for-automation',
        'part-8-professional-engineering/02-code-review-for-automation',
        'part-8-professional-engineering/03-scalable-automation-architecture',
      ],
    },
    {
      type: 'category',
      label: 'Projects',
      className: 'sidebar-wip',
      link: {
        type: 'generated-index',
        title: 'Projects',
        description:
          'Four applied projects. Briefs are available now; full supporting material is still under development.',
        slug: '/projects',
      },
      items: [
        'projects/project-1-test-result-analyzer',
        'projects/project-2-test-case-management',
        'projects/project-3-api-automation',
        'projects/project-4-web-automation',
      ],
    },
    {
      type: 'doc',
      id: 'capstone/00-capstone-overview',
      label: 'Capstone',
      className: 'sidebar-wip',
    },
    {
      type: 'category',
      label: 'Answer keys',
      collapsed: true,
      link: {type: 'doc', id: 'answer-keys/overview'},
      items: [
        {
          type: 'category',
          label: 'Part I',
          items: [
            'answer-keys/part-1/01-what-is-software-testing.answers',
            'answer-keys/part-1/02-manual-vs-automation-testing.answers',
            'answer-keys/part-1/03-test-strategy-and-the-test-pyramid.answers',
            'answer-keys/part-1/04-regression-smoke-sanity-and-test-quality.answers',
          ],
        },
        {
          type: 'category',
          label: 'Part II',
          items: [
            'answer-keys/part-2/01-thinking-like-a-programmer.answers',
            'answer-keys/part-2/02-data-types.answers',
            'answer-keys/part-2/03-variables-and-constants.answers',
            'answer-keys/part-2/04-operators.answers',
            'answer-keys/part-2/05-conditional-logic.answers',
            'answer-keys/part-2/06-loops.answers',
            'answer-keys/part-2/07-functions.answers',
            'answer-keys/part-2/08-arrays.answers',
            'answer-keys/part-2/09-objects.answers',
            'answer-keys/part-2/10-typescript-fundamentals.answers',
            'answer-keys/part-2/11-error-handling.answers',
            'answer-keys/part-2/12-asynchronous-programming.answers',
            'answer-keys/part-2/13-json.answers',
          ],
        },
        {
          type: 'category',
          label: 'Part III',
          items: [
            'answer-keys/part-3/01-principles-of-good-automated-tests.answers',
            'answer-keys/part-3/02-test-automation-architecture.answers',
          ],
        },
        {
          type: 'category',
          label: 'Part IV',
          items: [
            'answer-keys/part-4/01-http-fundamentals.answers',
            'answer-keys/part-4/02-rest-api-and-crud.answers',
            'answer-keys/part-4/03-designing-api-test-cases.answers',
            'answer-keys/part-4/04-playwright-api-testing-basics.answers',
            'answer-keys/part-4/05-playwright-api-write-operations.answers',
            'answer-keys/part-4/06-api-authentication-and-authorization.answers',
            'answer-keys/part-4/07-reusable-api-clients-and-models.answers',
            'answer-keys/part-4/08-api-test-data-and-environments.answers',
          ],
        },
        {
          type: 'category',
          label: 'Part V',
          className: 'sidebar-wip',
          items: [
            'answer-keys/part-5/01-playwright-fundamentals.answers',
            'answer-keys/part-5/02-locator-strategy.answers',
            'answer-keys/part-5/03-browser-actions.answers',
            'answer-keys/part-5/04-web-assertions.answers',
            'answer-keys/part-5/05-synchronization-and-flaky-tests.answers',
          ],
        },
        {
          type: 'category',
          label: 'Part VI',
          className: 'sidebar-wip',
          items: [
            'answer-keys/part-6/01-page-object-model.answers',
            'answer-keys/part-6/02-fixtures.answers',
            'answer-keys/part-6/03-authentication-strategies.answers',
            'answer-keys/part-6/04-test-data-management.answers',
            'answer-keys/part-6/05-configuration.answers',
            'answer-keys/part-6/06-cross-browser-and-mobile.answers',
            'answer-keys/part-6/07-parallel-execution-and-sharding.answers',
            'answer-keys/part-6/08-debugging-playwright-tests.answers',
            'answer-keys/part-6/09-diagnosing-flaky-tests.answers',
          ],
        },
        {
          type: 'category',
          label: 'Part VII',
          className: 'sidebar-wip',
          items: [
            'answer-keys/part-7/01-git-for-automation-engineers.answers',
            'answer-keys/part-7/02-jenkins-pipelines.answers',
            'answer-keys/part-7/03-docker-for-test-automation.answers',
          ],
        },
        {
          type: 'category',
          label: 'Part VIII',
          className: 'sidebar-wip',
          items: [
            'answer-keys/part-8/01-clean-code-for-automation.answers',
            'answer-keys/part-8/02-code-review-for-automation.answers',
            'answer-keys/part-8/03-scalable-automation-architecture.answers',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
